namaLengkap = input("Nama\t\t\t: ")
nim = input("NIM\t\t\t: ")
kelasParalel = int(input("Kelas Paralel\t\t: "))
ttl = input("Tempat/Tanggal Lahir\t: ")
alamat = input("Alamat\t\t\t: ")
hobby = input("Hobby\t\t\t: ")
noHP = input("No Handphone\t\t: ")

print("Output : ")
print("Nama\t\t\t: ", namaLengkap)
print("NIM\t\t\t: ", nim)
print("Kelas Paralel\t\t: ", kelasParalel)
print("Tempat/Tanggal Lahir\t: ", ttl)
print("Alamat\t\t\t: ", alamat)
print("Hobby\t\t\t: ", hobby)
print("No Handphone\t\t: ", noHP)