print("###################################")
print("#                                 #")
print("#  Muhammad Guntur Ricky Adhitya  #")
print("#          2410817310003          #")
print("#                                 #")
print("###################################")